### ISSUE TITLE
Prototype Lecturer Interface Backend

### ISSUE THREAD

**Issue by madebyTimo** [Gamify-IT/issues#148]
## Depends on

- Gamify-IT/issues#98

## Current situation

At most one lecturer can change the overworld from the frontend.

## Expected situation

Every lecturer with access to the frontend or the URL can access the same backend and modify his own state.

## DoD

- [ ] misplaced functionality from the frontend has been transferred to the backend
- [ ] backend is a working prototype
- [ ] (Optional) backend and frontend can communicate with each other

**Comment by madebyTimo** [comment]
@delvh Why do we need an Lecturer interface backend? Which function is misplaced in the frontend?

**Comment by delvh** [comment]
a) As we've determined: An instance of our platform should be able to host multiple lectures
b) each lecture should be configurable by its own lecturer
c) Implication: We need one central server to query our data from. Otherwise, things will get ugly: How do you ensure data consistency, or how do you specify which minigames even exist? Does each lecturer then need to supply a file stating which minigames exist, or what?
d) Even if we had a one-to-n relationship, not using a backend was already an anti-pattern I only agreed to because the vote was 10 to 1 against me. Our use case **screams** that we need a front- **and** a backend.

e) The only tasks of the front end should be `displaying` and `modifying` the current data. Everything else, such as querying all minigame backends or ensuring which minigames are present is the task of the backend.

**Comment by madebyTimo** [comment]
After a discussion we agreed to not make an explicite lecturer backend because it is mostly part of the overworld backend
