### ISSUE TITLE
Define Database data model for the Overworld

### ISSUE THREAD

**Issue by delvh** [Gamify-IT/issues#23]
### Current Behavior:
Currently we have no idea what kind of data we need to store for the overworld and in what form.

### Expected Behavior:
We need to know what kind of databases we need and what kind of information needs to be stored.

### DoD:
- [x] A Model for our overworld data exists
- [x] An appropriate Database has been chosen

**Comment by maexled** [comment]
# What kind of data do we need to store?
## Configuration specified data
- configure areas
   - active or not
   - dungeons
   - tasks 
   - [specific name?]
- configure dungeons 
   - active or not
   - tasks
   - [specific name?]
    
also check #38 for this

## Player-specific data
- location of the player
- completed tasks
- completed dungeons
- unlocked areas
- [carried items]
- [life points] 

# What kind of databases exists?
## SQL (Structured Query Language)
- MySQL or PostgreSQL
- relational database
- structured through relational data
- SQL is a good choice when working with related data.

## NoSQL
- Redis or Memcache
- non-relational database (key-value)
- allow a dynamic schema for unstructured data
- NoSQL is good when it’s more important that the availability of big data is fast
- NoSQL is also a good choice when there are large amounts of (or ever-changing) data sets or when working with flexible data models or needs that don't fit into a relational model

# What should we use?
## Configuration specified data
- clear point for SQL, the areas, dungeons, and tasks are all in relationships and do not get often updated.

## Player-specific data
- the player-specific data should also be stored in a SQL database.
- data could be updated often (like life points or carried items) and should be stored in a NoSQL database because performance could be a big point here.

... To be continued

**Comment by delvh** [comment]
What about Graph databases? Would they be useful in our case?

**Comment by maexled** [comment]
> What about Graph databases? Would they be useful in our case?

I am not that familiar with graph databases, maybe you can explain if you see it a bit other than me. As I know, graph databases are extremely nice if we have many relations. But I do not think that we have now or in the future that many relations, that a graph database is necessary or more efficient.

**Comment by delvh** [comment]
> As I know, graph databases are extremely nice if we have many relations

Yes, that's my knowledge about them as well. They are for example useful, when you have deeply nested structure trees like a `recipe` that has different `ingredient`s from different `producer`s that in turn are registered at the tax agency.
I only wanted to add this for completeness so that won't be "why didn't you use that instead?" in the end.
